# Numpy Arrays

**Getting started**

Numpy arrays are great alternatives to Python Lists. Some of the key advantages of Numpy arrays are that they are:
1. fast,
2. easy to work with, and
3. give users the opportunity to perform calculations across entire arrays.

In the following example, you will first create two Python lists. Then, you will import the numpy package and create numpy arrays out of the newly created lists.

In [ ]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

**Print out the type of np_height**

In [ ]:
print(type(height))

<class 'list'>


**Element-wise calculations**

Now we can perform element-wise calculations on height and weight. For example, you could take all 6 of the height and weight observations above, and calculate the BMI for each observation with a single equation. These operations are very fast and computationally efficient. They are particularly helpful when you have 1000s of observations in your data.

In [ ]:
# Calculate bmi
bmi = np_weight / np_height ** 2

# Print the result
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [ ]:
# Calculate bmi
bmi = weight / height ** 2

# Print the result
print(bmi)

TypeError: ignored

**Subsetting**

Another great feature of Numpy arrays is the ability to subset. For instance, if you wanted to know which observations in our BMI array are above 23, we could quickly subset it to find out.

In [ ]:
# For a boolean response
bmi > 25



array([False,  True,  True,  True, False,  True])

In [ ]:
# Print only those observations above 23
bmi[bmi > 27]

array([27.88755755, 28.75558507])