Lab -3 (Task)
1. Create a 1D NumPy array of integers from 10 to 20.
2. Reshape a 1D array of integers from 1 to 16 into a 4x4 matrix.
3.  Create a 2D array of shape (4, 5) with integers from 1 to 20 and access the element in the 3rd row and 4th column.
4. Create a 2D array with shape (4, 6) and from the 2nd and 3rd rows, slice elements from index 2 to index 5.
5. Convert a 1D array with 12 elements into a 3D array with shape (2, 3, 2). The outermost dimension will have 2 arrays that contain 3 arrays, each with 2 elements.
6. Create a 1D array of 15 elements and reshape it into a 3x5 matrix. Then, extract the 2nd row as a 1D array.
7. Create a 3D array with shape (2, 4, 3) and from the 1st array, slice elements from the 2nd and 3rd rows.
8. Create a filter array that will return only even elements from the original array.
9. quantities_sold = [15, 22, 8, 35, 12, 25]  and price_per_item = [2.99, 5.49, 9.99, 1.99, 3.49, 4.99]. Now, Convert quantities_sold and price_per_item to numpy arrays, calculate the total sales for each product as total_sales = quantities_sold * price_per_item, and print the total sales and average price per item.
10. math_scores = [88, 92, 85, 78, 90, 84] , science_scores = [91, 85, 87, 90, 88, 86] , english_scores = [82, 89, 88, 84, 91, 87]. Now, Convert math_scores, science_scores, and english_scores to numpy arrays, calculate each student’s average score across the three subjects, and print the averages.
11. Given the dictionary inventory = {"apple": 10, "banana": 5, "orange": 8, "grape": 3, "mango": 6}, write a program to update quantities with "banana": 3, "apple": 4, remove "grape", and check if "mango" exist or not.
12. Given the dictionary grades = {"Alice": 85, "Bob": 67, "Charlie": 90, "David": 72, "Eve": 58}, write a program to print students scoring above 70, add "Frank": 76, remove "Eve", and check if "George" exist or not.

In [ ]:
#Import block
#Run this block before running any code
import numpy as np

In [ ]:
#ans 1
arr1 = np.arange(10,21)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#ans 2
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#ans 3
arr3 = np.arange(1,21).reshape(4,5)
print(arr3[2,3])

14


In [ ]:
#ans 4
arr4 = np.arange(1,25).reshape(4,6)
print(arr4)
print(arr4[1:3,2:6])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[ 9 10 11 12]
 [15 16 17 18]]


In [ ]:
#ans 5
arr5 = np.arange(1,13).reshape(2,3,2)
print(arr5)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#ans 6
arr5 = np.arange(1,16).reshape(3,5)
print(arr5)
print(arr5[1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 6  7  8  9 10]


In [ ]:
#ans 7
arr6 = np.arange(1,25).reshape(2,4,3)
print(arr6)
print(arr6[0,1:3])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
[[4 5 6]
 [7 8 9]]


In [ ]:
#ans 8
arr7 = np.arange(1,11)
print(arr7)
filter_arr = arr7 % 2 == 0
newarr = arr7[filter_arr]
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


In [ ]:
#ans 9
arr8 = np.array([2.99, 5.49, 9.99, 1.99, 3.49, 4.99])
arr9 = np.array([15, 22, 8, 35, 12, 25])
total_sales = arr9 * arr8
print(total_sales)
print(np.average(total_sales))

[ 44.85 120.78  79.92  69.65  41.88 124.75]
80.305


In [ ]:
#ans 10
arr10 = np.array([88, 92, 85, 78, 90, 84])
arr11 = np.array([91, 85, 87, 90, 88, 86])
arr12 = np.array([82, 89, 88, 84, 91, 87])
print(np.average(arr10))
print(np.average(arr11))

86.16666666666667
87.83333333333333


In [ ]:
#ans 11
stock = {"apple": 10, "banana": 5, "orange": 8, "grape": 3, "mango": 6}
stock["banana"] = 3
stock["apple"] = 4
del stock["grape"]
print(stock)
print("mango" in stock)

{'apple': 4, 'banana': 3, 'orange': 8, 'mango': 6}
True


In [14]:
#ans 12
grades = {"Alice": 85, "Bob": 67, "Charlie": 90, "David": 72, "Eve": 58}
print(grades)
for key, value in grades.items():
    if value > 70:
        print(key)
grades["Frank"] = 76
del grades["Eve"]
print(grades)
print("George" in grades)

{'Alice': 85, 'Bob': 67, 'Charlie': 90, 'David': 72, 'Eve': 58}
Alice
Charlie
David
{'Alice': 85, 'Bob': 67, 'Charlie': 90, 'David': 72, 'Frank': 76}
False
